KassaOne/Models/CreditViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace KassaOne.Models
{
    public class CreditViewModel
    {
        [Required]
        public double CreditSum { get; set; }
        [Required]
        public int NumberOfPayments { get; set; }
        [Required]
        public double RatePerYear { get; set; }
        [Required]
        public int OptionValue { get; set; }
    }
}

KassaOne/Models/ErrorViewModel.cs
namespace KassaOne.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

KassaOne/Models/ResultViewModel.cs
using System.Collections.Generic;

namespace KassaOne.Models
{
    public class ResultViewModel
    {
        public List<ShowTable> ShowTable { get; set; }
        public ShowModel ShowModel { get; set; }
        public ResultViewModel(ShowModel showModel,List<ShowTable> showTable)
        {
            this.ShowModel = showModel;
            this.ShowTable = showTable;
        }
    }
}

KassaOne/Models/ShowModel.cs
using System.ComponentModel.DataAnnotations;

namespace KassaOne.Models
{
    public class ShowModel
    {
        [Required]
        public string CreditSum { get; set; }
        [Required]
        public string PurchasePrice { get; set; }
        [Required]
        public string CreditTime { get; set; }
        [Required]
        public string MonthlyPayment { get; set; }
        [Required]
        public string TotalOverpayment { get; set; }

    }
}

KassaOne/Models/ShowTable.cs
using System.ComponentModel.DataAnnotations;

namespace KassaOne.Models
{
    public class ShowTable
    {
        [Required]
        public int MonthNum { get; set; }
        [Required]
        public string MonthlyPayment { get; set; }
        [Required]
        public string MainPart { get; set; } //часть погашения долга от ежемесячного платежа
        [Required]
        public string PercentPart { get; set; } //часть погашения процентов от ежемесячного платежа
        [Required]
        public string RemainingAmount { get; set; }

        public ShowTable(int monthNum,string monthlyPayment, string mainPart, string percentPart,string remainingAmount)
        {
            MonthNum = monthNum;
            MonthlyPayment = monthlyPayment;
            MainPart = mainPart;
            PercentPart = percentPart;
            RemainingAmount = remainingAmount;
        }
    }
}

KassaOne/Controllers/KassaController.cs
using System;
using System.Collections.Generic;
using KassaOne.Models;
using Microsoft.AspNetCore.Mvc;

namespace KassaOne.Controllers
{
    public class KassaController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Index2()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(CreditViewModel creditModel)
        {
            creditModel.NumberOfPayments *= creditModel.OptionValue; // Количество платежей умножаем на период 15 дней - 2 два раза больше плятежей за месяц
            var showModel = ParseToShowModel(creditModel);
            var showTable = AnnualPaymentSchedule(creditModel.CreditSum,
                creditModel.RatePerYear,
                creditModel.NumberOfPayments,
                double.Parse(showModel.MonthlyPayment));

            var obj = new ResultViewModel (showModel,showTable );
            return View($"Index2",obj);
        }

        protected List<ShowTable> AnnualPaymentSchedule(double creditSum, double ratePerYear, double creditTime, double payment) // Метод расчета Аннуитетного платежа
        {
            var tableLst = new List<ShowTable>();
            for (int i = 0; i < creditTime; i++)
            {
                var percentage = creditSum * (ratePerYear / 100) / 12;
                var monthNum = i+1 ; //номер платежа 
                creditSum -= payment - percentage;
                var monthlyPayment = payment.ToString("N2"); //Ежемесячный платеж
                var payMain = (payment - percentage).ToString("N2"); //Платеж за основной долг
                var payPercent = percentage.ToString("N2"); //Платеж процента
                if (creditSum < 0)
                    creditSum = 0;
                var remainingAmount = creditSum.ToString("N2"); //Основной остаток
                tableLst.Add(new ShowTable(monthNum, monthlyPayment, payMain, payPercent, remainingAmount));
            }
            return tableLst;
        }
        public ShowModel ParseToShowModel(CreditViewModel creditModel)
        {
            var showModel = new ShowModel();
            var annuityCoefficient = CalculateAnnuity(creditModel);
            showModel.PurchasePrice = creditModel.CreditSum.ToString("N2");
            showModel.CreditTime = creditModel.NumberOfPayments.ToString();
            showModel.MonthlyPayment = annuityCoefficient.ToString("N2");
            showModel.CreditSum = (creditModel.NumberOfPayments * annuityCoefficient).ToString("N2");
            showModel.TotalOverpayment = ((creditModel.NumberOfPayments * annuityCoefficient) - double.Parse(showModel.PurchasePrice)).ToString("N2");
            return showModel;
        }
        public double CalculateAnnuity(CreditViewModel creditModel)
        {
            double monthlyRate = (creditModel.RatePerYear / 12) / 100;
            double periodNum = creditModel.NumberOfPayments;
            double annuityCoefficient = (monthlyRate * Math.Pow((1 + monthlyRate), periodNum)) / (Math.Pow((1 + monthlyRate), periodNum) - 1);
            double monthlyAnnuityPayment = annuityCoefficient * creditModel.CreditSum;
            return monthlyAnnuityPayment;
        }
    }
}

KassaOne/Views/Kassa/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@using KassaOne.Models;


<form method="post" action="~/Kassa/Index" enctype="multipart/form-data" class="form-group text-center">
    <div class="container">
        <div class="row">
            <div class="col-3"></div>
            <div class="col form-group">
                <label>Сумма Кредита(р.):</label>
                <br />
                <input type="number" name="CreditSum" class="form-control" min="1" required/>
                <br />
                <div class="row">
                    <div class="col">
                    <label>Срок кредитования(мес.):</label>
                    <br />
                    <input type="number" name="NumberOfPayments" class="form-control" min="1" required />
                    <br />
                    </div>
                    <div class="col-3">
                        <label for="inputState">Период</label>
                        <select name="OptionValue" id="inputState" class="form-control"  >
                            <option selected value="1">Месяц</option>
                            <option value="2">15 дней</option>
                            <option value="3">10 дней</option>
                        </select>
                    </div>
                </div>
                <label>Процентная ставка за год:</label>
                <br />
                <input type="number" name="RatePerYear" class="form-control" min="1" required/>
                <br /> 
                <input type="submit" value="Рассчитать" class="btn btn-success" />
            </div>
            <div class="col-3"></div>
        </div>
    </div>
</form>

KassaOne/Views/Kassa/Index2.cshtml
@using KassaOne.Models;

<div class="container">

    <div class="row ">
        <div class=" col-6">
            <div class="row f"> ПОЛНАЯ СТОИМОСТЬ КРЕДИТА @Model.ShowModel.CreditSum </div><hr>
            <div class="row">Стоимость покупки:  @Model.ShowModel.PurchasePrice</div><hr>
            <div class="row"> Кол-во платежей: @Model.ShowModel.CreditTime </div><hr>
            <div class="row">Ежемесячный платеж: @Model.ShowModel.MonthlyPayment</div><hr>
            <div class="row"> Общая сумма выплат: @Model.ShowModel.CreditSum </div><hr>
            <div class="row mb-5"> Общая переплата: @Model.ShowModel.TotalOverpayment</div>
        </div>
        <div class=" col-6">
            <div id="piechart" style="width: 700px; height: 400px;"></div>
        </div>
    </div>


</div>
<table class="table table-striped text-center">
    <caption>ГРАФИК ПЛАТЕЖЕЙ ПО КРЕДИТУ</caption>
    <tr>
        <th scope="col">№ Платежа</th>
        <th scope="col">Остаток по кредиту (руб.)</th>
        <th scope="col">Проценты (руб.)</th>
        <th scope="col">Погашение долга (руб.)</th>
        <th scope="col">Ежемесячный платеж (руб.)</th>
    </tr>
    @{ foreach (var item in Model.ShowTable)
        {
            <tr>
                <td><b>@item.MonthNum</b></td>
                <td>@item.RemainingAmount</td>
                <td>@item.PercentPart</td>
                <td>@item.MainPart</td>
                <td>@item.MonthlyPayment</td>
            </tr>
        }
    }

</table>

<script>
        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(drawChart);
function drawChart() {
    var data = google.visualization.arrayToDataTable([
        ['CreditSum', 'TotalOverpayment'],
        ['Сумма', @Json.Serialize(double.Parse(Model.ShowModel.CreditSum))],
        ['Переплата', @Json.Serialize(double.Parse(Model.ShowModel.TotalOverpayment))]

                    ]);

    var options = {
        title: 'CreditSum : TotalOverpayment '
    };

    var chart = new google.visualization.PieChart(document.getElementById('piechart'));

    chart.draw(data, options);
}

</script>

KassaOne/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript" src="~/js/site.js"></script>
<link rel="stylesheet" href="~/css/2.css">

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KassaOne</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Kassa" asp-action="Index">KassaOne</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>